// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAaFAu_FDneVj954kiKlrTLp3BDlhiOJw',
    appId: '1:28158895372:web:eda905124ed85a63719529',
    messagingSenderId: '28158895372',
    projectId: 'boltlog',
    authDomain: 'boltlog.firebaseapp.com',
    databaseURL: 'https://boltlog-default-rtdb.firebaseio.com',
    storageBucket: 'boltlog.firebasestorage.app',
    measurementId: 'G-7WF4HFCKD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuZTJgvpOr20n0yeK0s1OMQfiSSRWGSWI',
    appId: '1:28158895372:android:7da1f25f88abc96b719529',  // com.boltlog.app
    messagingSenderId: '28158895372',
    projectId: 'boltlog',
    databaseURL: 'https://boltlog-default-rtdb.firebaseio.com',
    storageBucket: 'boltlog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbfGIcMsgHtplxBAH4ibrUoWLd34qec8U',
    appId: '1:28158895372:ios:d081681c891266ed719529',
    messagingSenderId: '28158895372',
    projectId: 'boltlog',
    databaseURL: 'https://boltlog-default-rtdb.firebaseio.com',
    storageBucket: 'boltlog.firebasestorage.app',
    iosBundleId: 'com.example.boltlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbfGIcMsgHtplxBAH4ibrUoWLd34qec8U',
    appId: '1:28158895372:ios:d081681c891266ed719529',
    messagingSenderId: '28158895372',
    projectId: 'boltlog',
    databaseURL: 'https://boltlog-default-rtdb.firebaseio.com',
    storageBucket: 'boltlog.firebasestorage.app',
    iosBundleId: 'com.example.boltlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAaFAu_FDneVj954kiKlrTLp3BDlhiOJw',
    appId: '1:28158895372:web:ad5ae34939b05be2719529',
    messagingSenderId: '28158895372',
    projectId: 'boltlog',
    authDomain: 'boltlog.firebaseapp.com',
    databaseURL: 'https://boltlog-default-rtdb.firebaseio.com',
    storageBucket: 'boltlog.firebasestorage.app',
    measurementId: 'G-8B3QWRN373',
  );
}
