name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.3'
          channel: 'stable'

      - name: Get Dart & Flutter dependencies
        run: flutter pub get

      - name: Build Android release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: boltlog-apk
          path: build/app/outputs/flutter-apk/app-release.apk
<<<<<<< HEAD
=======

>>>>>>> cb8b7a6 (Initial commit for GitHub build)
